import os
import time
from github import Github, GithubException, Auth

# ==========================================
# ⚙️ CONFIGURATION SETTINGS
# ==========================================
GITHUB_TOKEN = os.getenv("GH_TOKEN") 
REPO_NAME = "Automation8248/Faceless-fact-yt"

# ==========================================
# 📊 HARDCODED DATA (Categories & Topics)
# ==========================================
DATA = [
    # ==================== ANIMALS ====================
    {'Topic': 'Animals', 'Category': 'Rhinos'},
    {'Topic': 'Animals', 'Category': 'Hippos'},
    {'Topic': 'Animals', 'Category': 'Cheetahs'},
    {'Topic': 'Animals', 'Category': 'Leopards'},
    {'Topic': 'Animals', 'Category': 'Jaguars'},
    {'Topic': 'Animals', 'Category': 'Hyenas'},
    {'Topic': 'Animals', 'Category': 'Meerkats'},
    {'Topic': 'Animals', 'Category': 'Sloths'},
    {'Topic': 'Armadillos', 'Category': 'Animals'},
    {'Topic': 'Animals', 'Category': 'Anteaters'},
    {'Topic': 'Animals', 'Category': 'Porcupines'},
    {'Topic': 'Animals', 'Category': 'Beavers'},
    {'Topic': 'Animals', 'Category': 'Otters'},
    {'Topic': 'Animals', 'Category': 'Badgers'},
    {'Topic': 'Animals', 'Category': 'Wolverines'},
    {'Topic': 'Animals', 'Category': 'Weasels'},
    {'Topic': 'Animals', 'Category': 'Raccoons'},
    {'Topic': 'Animals', 'Category': 'Skunks'},
    {'Topic': 'Animals', 'Category': 'Marmots'},
    {'Topic': 'Animals', 'Category': 'Squirrels'},
    {'Topic': 'Animals', 'Category': 'Chipmunks'},
    {'Topic': 'Animals', 'Category': 'Rats'},
    {'Topic': 'Animals', 'Category': 'Mice'},
    {'Topic': 'Animals', 'Category': 'Hamsters'},
    {'Topic': 'Animals', 'Category': 'Rabbits'},
    {'Topic': 'Animals', 'Category': 'Guinea Pigs'},
    {'Topic': 'Animals', 'Category': 'Ferrets'},
    {'Topic': 'Animals', 'Category': 'Platypuses'},
    {'Topic': 'Animals', 'Category': 'Echidnas'},
    {'Topic': 'Animals', 'Category': 'Wombats'},
    {'Topic': 'Animals', 'Category': 'Tasmanian Devils'},
    {'Topic': 'Animals', 'Category': 'Wallabies'},
    {'Topic': 'Animals', 'Category': 'Emus'},
    {'Topic': 'Animals', 'Category': 'Ostriches'},
    {'Topic': 'Animals', 'Category': 'Flamingos'},
    {'Topic': 'Animals', 'Category': 'Peacocks'},
    {'Topic': 'Animals', 'Category': 'Swans'},
    {'Topic': 'Animals', 'Category': 'Pelicans'},
    {'Topic': 'Animals', 'Category': 'Albatrosses'},
    {'Topic': 'Animals', 'Category': 'Hummingbirds'},
    {'Topic': 'Animals', 'Category': 'Woodpeckers'},
    {'Topic': 'Animals', 'Category': 'Crows'},
    {'Topic': 'Animals', 'Category': 'Ravens'},
    {'Topic': 'Animals', 'Category': 'Magpies'},
    {'Topic': 'Animals', 'Category': 'Kingfishers'},
    {'Topic': 'Animals', 'Category': 'Toucans'},
    {'Topic': 'Animals', 'Category': 'Geckos'},
    {'Topic': 'Animals', 'Category': 'Chameleons'},

    # ==================== HUMAN BODY ====================
    {'Topic': 'Human Body', 'Category': 'Pancreas'},
    {'Topic': 'Human Body', 'Category': 'Spleen'},
    {'Topic': 'Human Body', 'Category': 'Gallbladder'},
    {'Topic': 'Human Body', 'Category': 'Thyroid'},
    {'Topic': 'Human Body', 'Category': 'Adrenal Glands'},
    {'Topic': 'Human Body', 'Category': 'Pituitary Gland'},
    {'Topic': 'Human Body', 'Category': 'Spinal Cord'},
    {'Topic': 'Human Body', 'Category': 'Bone Marrow'},
    {'Topic': 'Human Body', 'Category': 'Cartilage'},
    {'Topic': 'Human Body', 'Category': 'Joints'},
    {'Topic': 'Human Body', 'Category': 'Ligaments'},
    {'Topic': 'Human Body', 'Category': 'Tendons'},
    {'Topic': 'Human Body', 'Category': 'Nerves'},
    {'Topic': 'Human Body', 'Category': 'Veins'},
    {'Topic': 'Human Body', 'Category': 'Arteries'},
    {'Topic': 'Human Body', 'Category': 'Capillaries'},
    {'Topic': 'Human Body', 'Category': 'Red Blood Cells'},
    {'Topic': 'Human Body', 'Category': 'White Blood Cells'},
    {'Topic': 'Human Body', 'Category': 'Platelets'},
    {'Topic': 'Human Body', 'Category': 'Hemoglobin'},
    {'Topic': 'Human Body', 'Category': 'Lymph'},
    {'Topic': 'Human Body', 'Category': 'Lymph Nodes'},
    {'Topic': 'Human Body', 'Category': 'Appendix'},
    {'Topic': 'Human Body', 'Category': 'Esophagus'},
    {'Topic': 'Human Body', 'Category': 'Colon'},
    {'Topic': 'Human Body', 'Category': 'Rectum'},
    {'Topic': 'Human Body', 'Category': 'Bladder'},
    {'Topic': 'Human Body', 'Category': 'Ureters'},
    {'Topic': 'Human Body', 'Category': 'Urethra'},
    {'Topic': 'Human Body', 'Category': 'Diaphragm'},
    {'Topic': 'Human Body', 'Category': 'Thymus'},
    {'Topic': 'Human Body', 'Category': 'Tonsils'},
    {'Topic': 'Human Body', 'Category': 'Salivary Glands'},
    {'Topic': 'Human Body', 'Category': 'Sweat Glands'},
    {'Topic': 'Human Body', 'Category': 'Oil Glands'},
    {'Topic': 'Human Body', 'Category': 'Pores'},
    {'Topic': 'Human Body', 'Category': 'Eyelashes'},
    {'Topic': 'Human Body', 'Category': 'Eyebrows'},
    {'Topic': 'Human Body', 'Category': 'Vocal Cords'},
    {'Topic': 'Human Body', 'Category': 'Eardrum'},
    {'Topic': 'Human Body', 'Category': 'Inner Ear'},
    {'Topic': 'Human Body', 'Category': 'Retina'},
    {'Topic': 'Human Body', 'Category': 'Cornea'},
    {'Topic': 'Human Body', 'Category': 'Iris'},
    {'Topic': 'Human Body', 'Category': 'Pupil'},
    {'Topic': 'Human Body', 'Category': 'Taste Buds'},
    {'Topic': 'Human Body', 'Category': 'Fingernails'},
    {'Topic': 'Human Body', 'Category': 'Body Temperature'},

    # ==================== HUMAN BRAIN ====================
    {'Topic': 'Human Brain', 'Category': 'Hippocampus'},
    {'Topic': 'Human Brain', 'Category': 'Amygdala'},
    {'Topic': 'Human Brain', 'Category': 'Cerebellum'},
    {'Topic': 'Human Brain', 'Category': 'Brainstem'},
    {'Topic': 'Human Brain', 'Category': 'Frontal Lobe'},
    {'Topic': 'Human Brain', 'Category': 'Parietal Lobe'},
    {'Topic': 'Human Brain', 'Category': 'Temporal Lobe'},
    {'Topic': 'Human Brain', 'Category': 'Occipital Lobe'},
    {'Topic': 'Human Brain', 'Category': 'Cerebral Cortex'},
    {'Topic': 'Human Brain', 'Category': 'Corpus Callosum'},
    {'Topic': 'Human Brain', 'Category': 'Glial Cells'},
    {'Topic': 'Human Brain', 'Category': 'Synapses'},
    {'Topic': 'Human Brain', 'Category': 'Dopamine'},
    {'Topic': 'Human Brain', 'Category': 'Serotonin'},
    {'Topic': 'Human Brain', 'Category': 'Oxytocin'},
    {'Topic': 'Human Brain', 'Category': 'Adrenaline'},
    {'Topic': 'Human Brain', 'Category': 'Cortisol'},
    {'Topic': 'Human Brain', 'Category': 'Endorphins'},
    {'Topic': 'Human Brain', 'Category': 'Brain Waves'},
    {'Topic': 'Human Brain', 'Category': 'Alpha Waves'},
    {'Topic': 'Human Brain', 'Category': 'Beta Waves'},
    {'Topic': 'Human Brain', 'Category': 'Theta Waves'},
    {'Topic': 'Human Brain', 'Category': 'Delta Waves'},
    {'Topic': 'Human Brain', 'Category': 'REM Sleep'},
    {'Topic': 'Human Brain', 'Category': 'Deep Sleep'},
    {'Topic': 'Human Brain', 'Category': 'Sleep Paralysis'},
    {'Topic': 'Human Brain', 'Category': 'Nightmares'},
    {'Topic': 'Human Brain', 'Category': 'False Memories'},
    {'Topic': 'Human Brain', 'Category': 'Working Memory'},
    {'Topic': 'Human Brain', 'Category': 'Long Term Memory'},
    {'Topic': 'Human Brain', 'Category': 'Short Term Memory'},
    {'Topic': 'Human Brain', 'Category': 'Procedural Memory'},
    {'Topic': 'Human Brain', 'Category': 'Episodic Memory'},
    {'Topic': 'Human Brain', 'Category': 'Semantic Memory'},
    {'Topic': 'Human Brain', 'Category': 'Motor Cortex'},
    {'Topic': 'Human Brain', 'Category': 'Visual Cortex'},
    {'Topic': 'Human Brain', 'Category': 'Auditory Cortex'},
    {'Topic': 'Human Brain', 'Category': 'Prefrontal Cortex'},
    {'Topic': 'Human Brain', 'Category': 'Brain Blood Flow'},
    {'Topic': 'Human Brain', 'Category': 'Brain Oxygen'},
    {'Topic': 'Human Brain', 'Category': 'Brain Energy'},
    {'Topic': 'Human Brain', 'Category': 'Brain Aging'},
    {'Topic': 'Human Brain', 'Category': 'Brain Development'},
    {'Topic': 'Human Brain', 'Category': 'Brain Recovery'},
    {'Topic': 'Human Brain', 'Category': 'Neural Networks'},
    {'Topic': 'Human Brain', 'Category': 'Brain Chemistry'},
    {'Topic': 'Human Brain', 'Category': 'Brain Signals'},
    {'Topic': 'Human Brain', 'Category': 'Brain Mapping'},
    {'Topic': 'Human Brain', 'Category': 'Brain Scans'},

    # ==================== PSYCHOLOGY ====================
    {'Topic': 'Psychology', 'Category': 'Confirmation Bias'},
    {'Topic': 'Psychology', 'Category': 'Anchoring Bias'},
    {'Topic': 'Psychology', 'Category': 'Availability Bias'},
    {'Topic': 'Psychology', 'Category': 'Halo Effect'},
    {'Topic': 'Psychology', 'Category': 'Dunning Kruger Effect'},
    {'Topic': 'Psychology', 'Category': 'Bystander Effect'},
    {'Topic': 'Psychology', 'Category': 'Stroop Effect'},
    {'Topic': 'Psychology', 'Category': 'Zeigarnik Effect'},
    {'Topic': 'Psychology', 'Category': 'Mere Exposure Effect'},
    {'Topic': 'Psychology', 'Category': 'Placebo Response'},
    {'Topic': 'Psychology', 'Category': 'Imposter Phenomenon'},
    {'Topic': 'Psychology', 'Category': 'Learned Helplessness'},
    {'Topic': 'Psychology', 'Category': 'Cognitive Dissonance'},
    {'Topic': 'Psychology', 'Category': 'Selective Attention'},
    {'Topic': 'Psychology', 'Category': 'Change Blindness'},
    {'Topic': 'Psychology', 'Category': 'Inattentional Blindness'},
    {'Topic': 'Psychology', 'Category': 'Social Proof'},
    {'Topic': 'Psychology', 'Category': 'Reciprocity'},
    {'Topic': 'Psychology', 'Category': 'Scarcity Effect'},
    {'Topic': 'Psychology', 'Category': 'Authority Effect'},
    {'Topic': 'Psychology', 'Category': 'Framing Effect'},
    {'Topic': 'Psychology', 'Category': 'Sunk Cost Fallacy'},
    {'Topic': 'Psychology', 'Category': 'Gambler Fallacy'},
    {'Topic': 'Psychology', 'Category': 'Optimism Bias'},
    {'Topic': 'Psychology', 'Category': 'Negativity Bias'},
    {'Topic': 'Psychology', 'Category': 'Self Serving Bias'},
    {'Topic': 'Psychology', 'Category': 'Actor Observer Bias'},
    {'Topic': 'Psychology', 'Category': 'False Consensus'},
    {'Topic': 'Psychology', 'Category': 'Fundamental Attribution Error'},
    {'Topic': 'Psychology', 'Category': 'Mere Ownership Effect'},
    {'Topic': 'Psychology', 'Category': 'Endowment Effect'},
    {'Topic': 'Psychology', 'Category': 'Peak End Rule'},
    {'Topic': 'Psychology', 'Category': 'Recency Effect'},
    {'Topic': 'Psychology', 'Category': 'Primacy Effect'},
    {'Topic': 'Psychology', 'Category': 'Serial Position Effect'},
    {'Topic': 'Psychology', 'Category': 'Spotlight Effect'},
    {'Topic': 'Psychology', 'Category': 'Cheerleader Effect'},
    {'Topic': 'Psychology', 'Category': 'Pygmalion Effect'},
    {'Topic': 'Psychology', 'Category': 'Hawthorne Effect'},
    {'Topic': 'Psychology', 'Category': 'Bobo Doll Experiment'},
    {'Topic': 'Psychology', 'Category': 'Stanford Prison Experiment'},
    {'Topic': 'Psychology', 'Category': 'Milgram Experiment'},
    {'Topic': 'Psychology', 'Category': 'Asch Conformity Experiment'},
    {'Topic': 'Psychology', 'Category': 'Attachment Styles'},
    {'Topic': 'Psychology', 'Category': 'Emotional Intelligence'},
    {'Topic': 'Psychology', 'Category': 'Self Esteem'},
    {'Topic': 'Psychology', 'Category': 'Self Control'},
    {'Topic': 'Psychology', 'Category': 'Procrastination'},
    {'Topic': 'Psychology', 'Category': 'Social Anxiety'},

    # ==================== OCEAN ====================
    {'Topic': 'Ocean', 'Category': 'Ocean Zones'},
    {'Topic': 'Ocean', 'Category': 'Sunlight Zone'},
    {'Topic': 'Ocean', 'Category': 'Twilight Zone'},
    {'Topic': 'Ocean', 'Category': 'Midnight Zone'},
    {'Topic': 'Ocean', 'Category': 'Ocean Floor'},
    {'Topic': 'Ocean', 'Category': 'Continental Shelf'},
    {'Topic': 'Ocean', 'Category': 'Continental Slope'},
    {'Topic': 'Ocean', 'Category': 'Abyssal Plain'},
    {'Topic': 'Ocean', 'Category': 'Mid Ocean Ridge'},
    {'Topic': 'Ocean', 'Category': 'Seamounts'},
    {'Topic': 'Ocean', 'Category': 'Guyots'},
    {'Topic': 'Ocean', 'Category': 'Ocean Trenches'},
    {'Topic': 'Ocean', 'Category': 'Underwater Mountains'},
    {'Topic': 'Ocean', 'Category': 'Kelp Forests'},
    {'Topic': 'Ocean', 'Category': 'Mangroves'},
    {'Topic': 'Ocean', 'Category': 'Seagrass'},
    {'Topic': 'Ocean', 'Category': 'Estuaries'},
    {'Topic': 'Ocean', 'Category': 'Salt Marshes'},
    {'Topic': 'Ocean', 'Category': 'Tidal Pools'},
    {'Topic': 'Ocean', 'Category': 'Sea Caves'},
    {'Topic': 'Ocean', 'Category': 'Underwater Rivers'},
    {'Topic': 'Ocean', 'Category': 'Brine Pools'},
    {'Topic': 'Ocean', 'Category': 'Ocean Deserts'},
    {'Topic': 'Ocean', 'Category': 'Dead Zones'},
    {'Topic': 'Ocean', 'Category': 'Ocean Gyres'},
    {'Topic': 'Ocean', 'Category': 'Upwelling'},
    {'Topic': 'Ocean', 'Category': 'Downwelling'},
    {'Topic': 'Ocean', 'Category': 'Rip Currents'},
    {'Topic': 'Ocean', 'Category': 'Rogue Waves'},
    {'Topic': 'Ocean', 'Category': 'Tsunami Waves'},
    {'Topic': 'Ocean', 'Category': 'Storm Surges'},
    {'Topic': 'Ocean', 'Category': 'King Tides'},
    {'Topic': 'Ocean', 'Category': 'Spring Tides'},
    {'Topic': 'Ocean', 'Category': 'Neap Tides'},
    {'Topic': 'Ocean', 'Category': 'Ocean Acidification'},
    {'Topic': 'Ocean', 'Category': 'Sea Level Rise'},
    {'Topic': 'Ocean', 'Category': 'Ocean Carbon'},
    {'Topic': 'Ocean', 'Category': 'Ocean Oxygen'},
    {'Topic': 'Ocean', 'Category': 'Ocean Heat'},
    {'Topic': 'Ocean', 'Category': 'Marine Migration'},
    {'Topic': 'Ocean', 'Category': 'Whale Migration'},
    {'Topic': 'Ocean', 'Category': 'Turtle Migration'},
    {'Topic': 'Ocean', 'Category': 'Fish Migration'},
    {'Topic': 'Ocean', 'Category': 'Marine Food Web'},
    {'Topic': 'Ocean', 'Category': 'Ocean Predators'},
    {'Topic': 'Ocean', 'Category': 'Ocean Herbivores'},
    {'Topic': 'Ocean', 'Category': 'Ocean Scavengers'},
    {'Topic': 'Ocean', 'Category': 'Ocean Symbiosis'},
    {'Topic': 'Ocean', 'Category': 'Ocean Conservation'},

    # ==================== DEEP SEA ====================
    {'Topic': 'Deep Sea', 'Category': 'Bathypelagic Zone'},
    {'Topic': 'Deep Sea', 'Category': 'Mesopelagic Zone'},
    {'Topic': 'Deep Sea', 'Category': 'Epipelagic Zone'},
    {'Topic': 'Deep Sea', 'Category': 'Pressure Adaptations'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Vision'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Hearing'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Smell'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Hunting'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Camouflage'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Migration'},
    {'Topic': 'Deep Sea', 'Category': 'Diel Vertical Migration'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Predators'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Scavengers'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Worms'},
    {'Topic': 'Deep Sea', 'Category': 'Tube Worms'},
    {'Topic': 'Deep Sea', 'Category': 'Giant Isopods'},
    {'Topic': 'Deep Sea', 'Category': 'Dumbo Octopus'},
    {'Topic': 'Deep Sea', 'Category': 'Frilled Sharks'},
    {'Topic': 'Deep Sea', 'Category': 'Sixgill Sharks'},
    {'Topic': 'Deep Sea', 'Category': 'Lanternfish'},
    {'Topic': 'Deep Sea', 'Category': 'Dragonfish'},
    {'Topic': 'Deep Sea', 'Category': 'Hatchetfish'},
    {'Topic': 'Deep Sea', 'Category': 'Viperfish'},
    {'Topic': 'Deep Sea', 'Category': 'Fangtooth Fish'},
    {'Topic': 'Deep Sea', 'Category': 'Barreleye Fish'},
    {'Topic': 'Deep Sea', 'Category': 'Blobfish'},
    {'Topic': 'Deep Sea', 'Category': 'Tripod Fish'},
    {'Topic': 'Deep Sea', 'Category': 'Grenadier Fish'},
    {'Topic': 'Deep Sea', 'Category': 'Siphonophores'},
    {'Topic': 'Deep Sea', 'Category': 'Comb Jellies'},
    {'Topic': 'Deep Sea', 'Category': 'Sea Spiders'},
    {'Topic': 'Deep Sea', 'Category': 'Sea Cucumbers'},
    {'Topic': 'Deep Sea', 'Category': 'Sea Pigs'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Snails'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Clams'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Shrimp'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Crabs'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Echinoderms'},
    {'Topic': 'Deep Sea', 'Category': 'Hydrothermal Vent Animals'},
    {'Topic': 'Deep Sea', 'Category': 'Vent Chemistry'},
    {'Topic': 'Deep Sea', 'Category': 'Black Smokers'},
    {'Topic': 'Deep Sea', 'Category': 'White Smokers'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Minerals'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Mining'},
    {'Topic': 'Deep Sea', 'Category': 'Submersibles'},
    {'Topic': 'Deep Sea', 'Category': 'ROVs'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Mapping'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Photography'},
    {'Topic': 'Deep Sea', 'Category': 'Deep Sea Exploration'},

    # ==================== SPACE ====================
    {'Topic': 'Space', 'Category': 'Mercury'},
    {'Topic': 'Space', 'Category': 'Venus'},
    {'Topic': 'Space', 'Category': 'Earth'},
    {'Topic': 'Space', 'Category': 'Mars'},
    {'Topic': 'Space', 'Category': 'Jupiter'},
    {'Topic': 'Space', 'Category': 'Saturn'},
    {'Topic': 'Space', 'Category': 'Uranus'},
    {'Topic': 'Space', 'Category': 'Neptune'},
    {'Topic': 'Space', 'Category': 'Sun'},
    {'Topic': 'Space', 'Category': 'Pluto'},
    {'Topic': 'Space', 'Category': 'Europa'},
    {'Topic': 'Space', 'Category': 'Titan'},
    {'Topic': 'Space', 'Category': 'Ganymede'},
    {'Topic': 'Space', 'Category': 'Callisto'},
    {'Topic': 'Space', 'Category': 'Io'},
    {'Topic': 'Space', 'Category': 'Enceladus'},
    {'Topic': 'Space', 'Category': 'Triton'},
    {'Topic': 'Space', 'Category': 'Phobos'},
    {'Topic': 'Space', 'Category': 'Deimos'},
    {'Topic': 'Space', 'Category': 'Charon'},
    {'Topic': 'Space', 'Category': 'Kuiper Belt'},
    {'Topic': 'Space', 'Category': 'Oort Cloud'},
    {'Topic': 'Space', 'Category': 'Heliosphere'},
    {'Topic': 'Space', 'Category': 'Solar Wind'},
    {'Topic': 'Space', 'Category': 'Solar Storms'},
    {'Topic': 'Space', 'Category': 'Solar Eclipse'},
    {'Topic': 'Space', 'Category': 'Lunar Eclipse'},
    {'Topic': 'Space', 'Category': 'Meteor Showers'},
    {'Topic': 'Space', 'Category': 'Supermoons'},
    {'Topic': 'Space', 'Category': 'Planetary Rings'},
    {'Topic': 'Space', 'Category': 'Planetary Atmospheres'},
    {'Topic': 'Space', 'Category': 'Space Debris'},
    {'Topic': 'Space', 'Category': 'Orbital Mechanics'},
    {'Topic': 'Space', 'Category': 'Zero Gravity'},
    {'Topic': 'Space', 'Category': 'Microgravity'},
    {'Topic': 'Space', 'Category': 'Astronauts'},
    {'Topic': 'Space', 'Category': 'Spacewalks'},
    {'Topic': 'Space', 'Category': 'Rocket Engines'},
    {'Topic': 'Space', 'Category': 'Reusable Rockets'},
    {'Topic': 'Space', 'Category': 'Launch Systems'},
    {'Topic': 'Space', 'Category': 'Space Probes'},
    {'Topic': 'Space', 'Category': 'Rovers'},
    {'Topic': 'Space', 'Category': 'Lunar Rovers'},
    {'Topic': 'Space', 'Category': 'Mars Rovers'},
    {'Topic': 'Space', 'Category': 'Space Telescopes'},
    {'Topic': 'Space', 'Category': 'Hubble Telescope'},
    {'Topic': 'Space', 'Category': 'James Webb Telescope'},
    {'Topic': 'Space', 'Category': 'Space Observatories'},

    # ==================== UNIVERSE ====================
    {'Topic': 'Universe', 'Category': 'Dark Energy'},
    {'Topic': 'Universe', 'Category': 'Dark Matter'},
    {'Topic': 'Universe', 'Category': 'Cosmic Inflation'},
    {'Topic': 'Universe', 'Category': 'Cosmic Microwave Background'},
    {'Topic': 'Universe', 'Category': 'Cosmic Horizon'},
    {'Topic': 'Universe', 'Category': 'Observable Universe'},
    {'Topic': 'Universe', 'Category': 'Universe Expansion'},
    {'Topic': 'Universe', 'Category': 'Hubble Constant'},
    {'Topic': 'Universe', 'Category': 'Cosmic Redshift'},
    {'Topic': 'Universe', 'Category': 'Cosmic Voids'},
    {'Topic': 'Universe', 'Category': 'Galaxy Filaments'},
    {'Topic': 'Universe', 'Category': 'Galaxy Superclusters'},
    {'Topic': 'Universe', 'Category': 'Galaxy Groups'},
    {'Topic': 'Universe', 'Category': 'Dwarf Galaxies'},
    {'Topic': 'Universe', 'Category': 'Spiral Galaxies'},
    {'Topic': 'Universe', 'Category': 'Elliptical Galaxies'},
    {'Topic': 'Universe', 'Category': 'Irregular Galaxies'},
    {'Topic': 'Universe', 'Category': 'Active Galaxies'},
    {'Topic': 'Universe', 'Category': 'Quasars'},
    {'Topic': 'Universe', 'Category': 'Pulsars'},
    {'Topic': 'Universe', 'Category': 'Neutron Stars'},
    {'Topic': 'Universe', 'Category': 'White Dwarfs'},
    {'Topic': 'Universe', 'Category': 'Red Giants'},
    {'Topic': 'Universe', 'Category': 'Brown Dwarfs'},
    {'Topic': 'Universe', 'Category': 'Protostars'},
    {'Topic': 'Universe', 'Category': 'Star Clusters'},
    {'Topic': 'Universe', 'Category': 'Globular Clusters'},
    {'Topic': 'Universe', 'Category': 'Open Clusters'},
    {'Topic': 'Universe', 'Category': 'Stellar Nurseries'},
    {'Topic': 'Universe', 'Category': 'Stellar Evolution'},
    {'Topic': 'Universe', 'Category': 'Star Birth'},
    {'Topic': 'Universe', 'Category': 'Star Death'},
    {'Topic': 'Universe', 'Category': 'Supernova Remnants'},
    {'Topic': 'Universe', 'Category': 'Gamma Ray Bursts'},
    {'Topic': 'Universe', 'Category': 'Cosmic Rays'},
    {'Topic': 'Universe', 'Category': 'Neutrinos'},
    {'Topic': 'Universe', 'Category': 'Antimatter'},
    {'Topic': 'Universe', 'Category': 'Matter Antimatter'},
    {'Topic': 'Universe', 'Category': 'Quantum Vacuum'},
    {'Topic': 'Universe', 'Category': 'Vacuum Energy'},
    {'Topic': 'Universe', 'Category': 'Cosmic Entropy'},
    {'Topic': 'Universe', 'Category': 'Arrow of Time'},
    {'Topic': 'Universe', 'Category': 'Space Time'},
    {'Topic': 'Universe', 'Category': 'Extra Dimensions'},
    {'Topic': 'Universe', 'Category': 'Cosmic Strings'},
    {'Topic': 'Universe', 'Category': 'Gravitational Waves'},
    {'Topic': 'Universe', 'Category': 'Cosmic Structure'},
    {'Topic': 'Universe', 'Category': 'Universe Fate'},
    {'Topic': 'Universe', 'Category': 'Heat Death'},

    # ==================== BLACK HOLES ====================
    {'Topic': 'Black Holes', 'Category': 'Supermassive Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Intermediate Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Primordial Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Spin'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Mass'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Jets'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Shadows'},
    {'Topic': 'Black Holes', 'Category': 'Hawking Radiation'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Evaporation'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Entropy'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Temperature'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Mergers'},
    {'Topic': 'Black Holes', 'Category': 'Binary Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Binaries'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Accretion'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Disks'},
    {'Topic': 'Black Holes', 'Category': 'Relativistic Jets'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Magnetism'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Gravity'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Tidal Forces'},
    {'Topic': 'Black Holes', 'Category': 'Spaghettification'},
    {'Topic': 'Black Holes', 'Category': 'Gravitational Time Dilation'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Orbits'},
    {'Topic': 'Black Holes', 'Category': 'Photon Sphere'},
    {'Topic': 'Black Holes', 'Category': 'Ergosphere'},
    {'Topic': 'Black Holes', 'Category': 'Kerr Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Schwarzschild Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Reissner Nordstrom Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Rotating Black Holes'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Mysterious Signals'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Information Paradox'},
    {'Topic': 'Black Holes', 'Category': 'Firewall Paradox'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Thermodynamics'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Entanglement'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Quantum Effects'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Formation'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Growth'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Feeding'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Collision'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Recoil'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Detection'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Imaging'},
    {'Topic': 'Black Holes', 'Category': 'Event Horizon Telescope'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Candidates'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Mass Gap'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Population'},
    {'Topic': 'Black Holes', 'Category': 'Black Hole Mysteries'},

    # ==================== ALIEN LIFE ====================
    {'Topic': 'Alien Life', 'Category': 'Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Technosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Drake Equation'},
    {'Topic': 'Alien Life', 'Category': 'Fermi Paradox'},
    {'Topic': 'Alien Life', 'Category': 'SETI Searches'},
    {'Topic': 'Alien Life', 'Category': 'Radio Signals'},
    {'Topic': 'Alien Life', 'Category': 'Fast Radio Bursts'},
    {'Topic': 'Alien Life', 'Category': 'Alien Microbes'},
    {'Topic': 'Alien Life', 'Category': 'Alien Intelligence'},
    {'Topic': 'Alien Life', 'Category': 'Alien Technology'},
    {'Topic': 'Alien Life', 'Category': 'Alien Communication'},
    {'Topic': 'Alien Life', 'Category': 'Alien Languages'},
    {'Topic': 'Alien Life', 'Category': 'Alien Civilizations'},
    {'Topic': 'Alien Life', 'Category': 'Kardashev Scale'},
    {'Topic': 'Alien Life', 'Category': 'Dyson Spheres'},
    {'Topic': 'Alien Life', 'Category': 'Dyson Swarms'},
    {'Topic': 'Alien Life', 'Category': 'Megastructures'},
    {'Topic': 'Alien Life', 'Category': 'Habitable Moons'},
    {'Topic': 'Alien Life', 'Category': 'Ocean Worlds'},
    {'Topic': 'Alien Life', 'Category': 'Subsurface Oceans'},
    {'Topic': 'Alien Life', 'Category': 'Europa Ocean'},
    {'Topic': 'Alien Life', 'Category': 'Enceladus Plumes'},
    {'Topic': 'Alien Life', 'Category': 'Titan Chemistry'},
    {'Topic': 'Alien Life', 'Category': 'Mars Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Mars Methane'},
    {'Topic': 'Alien Life', 'Category': 'Venus Clouds'},
    {'Topic': 'Alien Life', 'Category': 'Exoplanet Atmospheres'},
    {'Topic': 'Alien Life', 'Category': 'Oxygen Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Methane Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Water Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Atmospheric Biosignatures'},
    {'Topic': 'Alien Life', 'Category': 'Red Dwarf Habitable Zones'},
    {'Topic': 'Alien Life', 'Category': 'Sunlike Stars'},
    {'Topic': 'Alien Life', 'Category': 'Super Earth Habitability'},
    {'Topic': 'Alien Life', 'Category': 'Tidal Locking'},
    {'Topic': 'Alien Life', 'Category': 'Alien Evolution'},
    {'Topic': 'Alien Life', 'Category': 'Alien Ecosystems'},
    {'Topic': 'Alien Life', 'Category': 'Alien Oceans'},
    {'Topic': 'Alien Life', 'Category': 'Alien Atmospheres'},
    {'Topic': 'Alien Life', 'Category': 'Alien Biochemistry'},
    {'Topic': 'Alien Life', 'Category': 'Alternative Biochemistry'},
    {'Topic': 'Alien Life', 'Category': 'Silicon Life'},
    {'Topic': 'Alien Life', 'Category': 'Extremophile Life'},
    {'Topic': 'Alien Life', 'Category': 'Panspermia'},
    {'Topic': 'Alien Life', 'Category': 'Directed Panspermia'},
    {'Topic': 'Alien Life', 'Category': 'Interstellar Life'},
    {'Topic': 'Alien Life', 'Category': 'Life Around Pulsars'},
    {'Topic': 'Alien Life', 'Category': 'Life Around Red Dwarfs'},
    {'Topic': 'Alien Life', 'Category': 'Alien Archaeology'},

    # ==================== DINOSAURS ====================
    {'Topic': 'Dinosaurs', 'Category': 'Allosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Ankylosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Iguanodon'},
    {'Topic': 'Dinosaurs', 'Category': 'Parasaurolophus'},
    {'Topic': 'Dinosaurs', 'Category': 'Diplodocus'},
    {'Topic': 'Dinosaurs', 'Category': 'Spinosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Therizinosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Carnotaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Giganotosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Argentinosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Apatosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Baryonyx'},
    {'Topic': 'Dinosaurs', 'Category': 'Compsognathus'},
    {'Topic': 'Dinosaurs', 'Category': 'Deinonychus'},
    {'Topic': 'Dinosaurs', 'Category': 'Dilophosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Gallimimus'},
    {'Topic': 'Dinosaurs', 'Category': 'Maiasaura'},
    {'Topic': 'Dinosaurs', 'Category': 'Microraptor'},
    {'Topic': 'Dinosaurs', 'Category': 'Pachycephalosaurus'},
    {'Topic': 'Dinosaurs', 'Category': 'Protoceratops'},
    {'Topic': 'Dinosaurs', 'Category': 'Sauropods'},
    {'Topic': 'Dinosaurs', 'Category': 'Theropods'},
    {'Topic': 'Dinosaurs', 'Category': 'Ceratopsians'},
    {'Topic': 'Dinosaurs', 'Category': 'Hadrosaurs'},
    {'Topic': 'Dinosaurs', 'Category': 'Ankylosaurs'},
    {'Topic': 'Dinosaurs', 'Category': 'Stegosaurs'},
    {'Topic': 'Dinosaurs', 'Category': 'Raptors'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Feathers'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Skin'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Teeth'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Claws'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Tails'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Horns'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Crests'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Footprints'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Nests'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Parenting'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Communication'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Intelligence'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Speed'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Size'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Diets'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Herds'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Predators'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Diseases'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Fossilization'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Paleontology'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Evolution'},
    {'Topic': 'Dinosaurs', 'Category': 'Dinosaur Extinction'},

    # ==================== ANCIENT MYSTERIES ====================
    {'Topic': 'Ancient Mysteries', 'Category': 'Gobekli Tepe'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Moai Statues'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Astronomical Sites'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Observatories'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Star Maps'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Calendars'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Navigation'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Machines'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Batteries'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Computers'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Roman Concrete'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Damascus Steel'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Greek Fire'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Glass'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Plumbing'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Roads'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Bridges'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Aqueducts'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Tunnels'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Mines'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Shipwrecks'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Burial Sites'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Mummies'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Bog Bodies'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Frozen Mummies'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient DNA'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Languages'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Undeciphered Scripts'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Voynich Manuscript'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Rongorongo Script'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Phaistos Disc'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Dead Sea Scrolls'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Copper Scroll'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Roman Dodecahedrons'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Lycurgus Cup'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Nebraska Man'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Crystal Skulls'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Baghdad Battery'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Sacsayhuaman'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Puma Punku'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Baalbek Stones'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Longyou Caves'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Derinkuyu Underground City'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Petra Engineering'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Roman Underground Tunnels'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Medical Practices'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Surgical Tools'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Poison Knowledge'},
    {'Topic': 'Ancient Mysteries', 'Category': 'Ancient Mystery Objects'},

    # ==================== UNSOLVED MYSTERIES ====================
    {'Topic': 'Unsolved Mysteries', 'Category': 'D B Cooper'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Mary Celeste'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Dyatlov Pass'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Roanoke Colony'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Somerton Man'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Zodiac Killer'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Jack the Ripper'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Black Dahlia'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Amelia Earhart'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'MH370'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Mary Magdalene Relics'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Oak Island'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Flannan Isles'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Sodder Children'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Isdal Woman'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Tamam Shud'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lead Masks Case'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Max Headroom Incident'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Wow Signal'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Taos Hum'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Bloop Sound'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Hum Phenomenon'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Voynich Manuscript Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Zodiac Ciphers'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Beale Ciphers'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Dorabella Cipher'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Kryptos'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Somerton Cipher'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Phaistos Disc Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Rongorongo Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Ghost Rockets'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Green Children of Woolpit'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Man in the Iron Mask'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Princes in the Tower'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lost Amber Room'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lost Faberge Eggs'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Missing Roman Legions'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lost Treasure Fleets'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lost Franklin Expedition'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Lost Franklin Ships'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'USS Cyclops'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Ghost Ship Kaz II'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'MV Joyita'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Carroll A Deering'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Patty Hearst Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Tunguska Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Wow Signal Mystery'},
    {'Topic': 'Unsolved Mysteries', 'Category': 'Unidentified Human History'},

    # ==================== SCIENCE MYSTERIES ====================
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Consciousness'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Life'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Time'},
    {'Topic': 'Science Mysteries', 'Category': 'Nature of Reality'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Measurement'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Entanglement'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Superposition'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Tunneling'},
    {'Topic': 'Science Mysteries', 'Category': 'Wave Particle Duality'},
    {'Topic': 'Science Mysteries', 'Category': 'Measurement Problem'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Gravity'},
    {'Topic': 'Science Mysteries', 'Category': 'Theory of Everything'},
    {'Topic': 'Science Mysteries', 'Category': 'Hierarchy Problem'},
    {'Topic': 'Science Mysteries', 'Category': 'Strong CP Problem'},
    {'Topic': 'Science Mysteries', 'Category': 'Muon Anomaly'},
    {'Topic': 'Science Mysteries', 'Category': 'Matter Asymmetry'},
    {'Topic': 'Science Mysteries', 'Category': 'Antimatter Mystery'},
    {'Topic': 'Science Mysteries', 'Category': 'Neutrino Mystery'},
    {'Topic': 'Science Mysteries', 'Category': 'Proton Decay'},
    {'Topic': 'Science Mysteries', 'Category': 'Dark Matter Detection'},
    {'Topic': 'Science Mysteries', 'Category': 'Dark Energy Nature'},
    {'Topic': 'Science Mysteries', 'Category': 'Hubble Tension'},
    {'Topic': 'Science Mysteries', 'Category': 'Cosmic Inflation'},
    {'Topic': 'Science Mysteries', 'Category': 'Vacuum Energy'},
    {'Topic': 'Science Mysteries', 'Category': 'Cosmological Constant'},
    {'Topic': 'Science Mysteries', 'Category': 'Arrow of Time'},
    {'Topic': 'Science Mysteries', 'Category': 'Entropy Mystery'},
    {'Topic': 'Science Mysteries', 'Category': 'Black Hole Information'},
    {'Topic': 'Science Mysteries', 'Category': 'Quantum Biology'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Aging'},
    {'Topic': 'Science Mysteries', 'Category': 'Human Longevity'},
    {'Topic': 'Science Mysteries', 'Category': 'Regeneration'},
    {'Topic': 'Science Mysteries', 'Category': 'Why We Dream'},
    {'Topic': 'Science Mysteries', 'Category': 'Memory Formation'},
    {'Topic': 'Science Mysteries', 'Category': 'Memory Storage'},
    {'Topic': 'Science Mysteries', 'Category': 'Consciousness Measurement'},
    {'Topic': 'Science Mysteries', 'Category': 'Placebo Mechanism'},
    {'Topic': 'Science Mysteries', 'Category': 'Gut Brain Connection'},
    {'Topic': 'Science Mysteries', 'Category': 'Microbiome Mystery'},
    {'Topic': 'Science Mysteries', 'Category': 'Animal Navigation'},
    {'Topic': 'Science Mysteries', 'Category': 'Bird Migration'},
    {'Topic': 'Science Mysteries', 'Category': 'Animal Magnetoreception'},
    {'Topic': 'Science Mysteries', 'Category': 'Plant Intelligence'},
    {'Topic': 'Science Mysteries', 'Category': 'Plant Communication'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Language'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Intelligence'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Mathematics'},
    {'Topic': 'Science Mysteries', 'Category': 'Origin of Creativity'},
    {'Topic': 'Science Mysteries', 'Category': 'Unsolved Physics'},

    # ==================== HUMAN SURVIVAL ====================
    {'Topic': 'Human Survival', 'Category': 'Hypothermia'},
    {'Topic': 'Human Survival', 'Category': 'Heatstroke'},
    {'Topic': 'Human Survival', 'Category': 'Frostbite'},
    {'Topic': 'Human Survival', 'Category': 'Oxygen Deprivation'},
    {'Topic': 'Human Survival', 'Category': 'Carbon Monoxide'},
    {'Topic': 'Human Survival', 'Category': 'Decompression Sickness'},
    {'Topic': 'Human Survival', 'Category': 'Altitude Sickness'},
    {'Topic': 'Human Survival', 'Category': 'Hypoxia'},
    {'Topic': 'Human Survival', 'Category': 'Water Survival'},
    {'Topic': 'Human Survival', 'Category': 'Food Survival'},
    {'Topic': 'Human Survival', 'Category': 'Shelter Building'},
    {'Topic': 'Human Survival', 'Category': 'Fire Making'},
    {'Topic': 'Human Survival', 'Category': 'Water Purification'},
    {'Topic': 'Human Survival', 'Category': 'Foraging'},
    {'Topic': 'Human Survival', 'Category': 'Navigation'},
    {'Topic': 'Human Survival', 'Category': 'Compass Survival'},
    {'Topic': 'Human Survival', 'Category': 'Map Reading'},
    {'Topic': 'Human Survival', 'Category': 'Signal Fires'},
    {'Topic': 'Human Survival', 'Category': 'Emergency Signals'},
    {'Topic': 'Human Survival', 'Category': 'Rescue Beacons'},
    {'Topic': 'Human Survival', 'Category': 'Desert Navigation'},
    {'Topic': 'Human Survival', 'Category': 'Jungle Navigation'},
    {'Topic': 'Human Survival', 'Category': 'Mountain Navigation'},
    {'Topic': 'Human Survival', 'Category': 'Cave Survival'},
    {'Topic': 'Human Survival', 'Category': 'Avalanche Rescue'},
    {'Topic': 'Human Survival', 'Category': 'Flood Rescue'},
    {'Topic': 'Human Survival', 'Category': 'Earthquake Preparedness'},
    {'Topic': 'Human Survival', 'Category': 'Tsunami Preparedness'},
    {'Topic': 'Human Survival', 'Category': 'Wildfire Survival'},
    {'Topic': 'Human Survival', 'Category': 'Storm Survival'},
    {'Topic': 'Human Survival', 'Category': 'Hurricane Survival'},
    {'Topic': 'Human Survival', 'Category': 'Tornado Survival'},
    {'Topic': 'Human Survival', 'Category': 'Lightning Safety'},
    {'Topic': 'Human Survival', 'Category': 'Snakebite Survival'},
    {'Topic': 'Human Survival', 'Category': 'Animal Attack Survival'},
    {'Topic': 'Human Survival', 'Category': 'Ocean Survival'},
    {'Topic': 'Human Survival', 'Category': 'Lifeboat Survival'},
    {'Topic': 'Human Survival', 'Category': 'Raft Survival'},
    {'Topic': 'Human Survival', 'Category': 'Wilderness First Aid'},
    {'Topic': 'Human Survival', 'Category': 'Emergency Medicine'},
    {'Topic': 'Human Survival', 'Category': 'Survival Equipment'},
    {'Topic': 'Human Survival', 'Category': 'Emergency Food'},
    {'Topic': 'Human Survival', 'Category': 'Emergency Water'},
    {'Topic': 'Human Survival', 'Category': 'Survival Clothing'},
    {'Topic': 'Human Survival', 'Category': 'Thermal Protection'},
    {'Topic': 'Human Survival', 'Category': 'Shelter Insulation'},
    {'Topic': 'Human Survival', 'Category': 'Psychological Survival'},
    {'Topic': 'Human Survival', 'Category': 'Group Survival'},
    {'Topic': 'Human Survival', 'Category': 'Long Term Survival'},

    # ==================== DANGEROUS ANIMALS ====================
    {'Topic': 'Dangerous Animals', 'Category': 'Hippos'},
    {'Topic': 'Dangerous Animals', 'Category': 'Leopards'},
    {'Topic': 'Dangerous Animals', 'Category': 'Jaguars'},
    {'Topic': 'Dangerous Animals', 'Category': 'Hyenas'},
    {'Topic': 'Dangerous Animals', 'Category': 'Cape Buffalo'},
    {'Topic': 'Dangerous Animals', 'Category': 'Polar Bears'},
    {'Topic': 'Dangerous Animals', 'Category': 'Grizzly Bears'},
    {'Topic': 'Dangerous Animals', 'Category': 'Komodo Dragons'},
    {'Topic': 'Dangerous Animals', 'Category': 'Cassowaries'},
    {'Topic': 'Dangerous Animals', 'Category': 'Stonefish'},
    {'Topic': 'Dangerous Animals', 'Category': 'Cone Snails'},
    {'Topic': 'Dangerous Animals', 'Category': 'Blue Ringed Octopus'},
    {'Topic': 'Dangerous Animals', 'Category': 'Box Jellyfish'},
    {'Topic': 'Dangerous Animals', 'Category': 'Irukandji Jellyfish'},
    {'Topic': 'Dangerous Animals', 'Category': 'Portuguese Man O War'},
    {'Topic': 'Dangerous Animals', 'Category': 'Pufferfish'},
    {'Topic': 'Dangerous Animals', 'Category': 'Blue Dragon'},
    {'Topic': 'Dangerous Animals', 'Category': 'Sea Snakes'},
    {'Topic': 'Dangerous Animals', 'Category': 'Taipan'},
    {'Topic': 'Dangerous Animals', 'Category': 'Mamba'},
    {'Topic': 'Dangerous Animals', 'Category': 'King Cobra'},
    {'Topic': 'Dangerous Animals', 'Category': 'Boomslang'},
    {'Topic': 'Dangerous Animals', 'Category': 'Russells Viper'},
    {'Topic': 'Dangerous Animals', 'Category': 'Saw Scaled Viper'},
    {'Topic': 'Dangerous Animals', 'Category': 'Fer De Lance'},
    {'Topic': 'Dangerous Animals', 'Category': 'Black Widow'},
    {'Topic': 'Dangerous Animals', 'Category': 'Brown Recluse'},
    {'Topic': 'Dangerous Animals', 'Category': 'Sydney Funnel Web'},
    {'Topic': 'Dangerous Animals', 'Category': 'Brazilian Wandering Spider'},
    {'Topic': 'Dangerous Animals', 'Category': 'Deathstalker Scorpion'},
    {'Topic': 'Dangerous Animals', 'Category': 'Bark Scorpion'},
    {'Topic': 'Dangerous Animals', 'Category': 'Goliath Birdeater'},
    {'Topic': 'Dangerous Animals', 'Category': 'Mosquito'},
    {'Topic': 'Dangerous Animals', 'Category': 'Tsetse Fly'},
    {'Topic': 'Dangerous Animals', 'Category': 'Kissing Bug'},
    {'Topic': 'Dangerous Animals', 'Category': 'Driver Ants'},
    {'Topic': 'Dangerous Animals', 'Category': 'Bullet Ants'},
    {'Topic': 'Dangerous Animals', 'Category': 'Fire Ants'},
    {'Topic': 'Dangerous Animals', 'Category': 'Africanized Bees'},
    {'Topic': 'Dangerous Animals', 'Category': 'Hornets'},
    {'Topic': 'Dangerous Animals', 'Category': 'Wild Boars'},
    {'Topic': 'Dangerous Animals', 'Category': 'Moose'},
    {'Topic': 'Dangerous Animals', 'Category': 'Bison'},
    {'Topic': 'Dangerous Animals', 'Category': 'Cassowary'},
    {'Topic': 'Dangerous Animals', 'Category': 'Wolverine'},
    {'Topic': 'Dangerous Animals', 'Category': 'Tasmanian Devil'},
    {'Topic': 'Dangerous Animals', 'Category': 'African Wild Dogs'},
    {'Topic': 'Dangerous Animals', 'Category': 'Baboon'},
    {'Topic': 'Dangerous Animals', 'Category': 'Macaques'},

    # ==================== EXTREME PLACES ====================
    {'Topic': 'Extreme Places', 'Category': 'K2'},
    {'Topic': 'Extreme Places', 'Category': 'Karakoram'},
    {'Topic': 'Extreme Places', 'Category': 'Denali'},
    {'Topic': 'Extreme Places', 'Category': 'Aconcagua'},
    {'Topic': 'Extreme Places', 'Category': 'Mauna Kea'},
    {'Topic': 'Extreme Places', 'Category': 'Mauna Loa'},
    {'Topic': 'Extreme Places', 'Category': 'Kola Superdeep Borehole'},
    {'Topic': 'Extreme Places', 'Category': 'Challenger Deep'},
    {'Topic': 'Extreme Places', 'Category': 'Puerto Rico Trench'},
    {'Topic': 'Extreme Places', 'Category': 'Tonga Trench'},
    {'Topic': 'Extreme Places', 'Category': 'Java Trench'},
    {'Topic': 'Extreme Places', 'Category': 'Congo Canyon'},
    {'Topic': 'Extreme Places', 'Category': 'Antarctic Plateau'},
    {'Topic': 'Extreme Places', 'Category': 'McMurdo Dry Valleys'},
    {'Topic': 'Extreme Places', 'Category': 'Wadi Halfa'},
    {'Topic': 'Extreme Places', 'Category': 'Lut Desert'},
    {'Topic': 'Extreme Places', 'Category': 'Sonoran Desert'},
    {'Topic': 'Extreme Places', 'Category': 'Gobi Desert'},
    {'Topic': 'Extreme Places', 'Category': 'Namib Desert'},
    {'Topic': 'Extreme Places', 'Category': 'Kalahari Desert'},
    {'Topic': 'Extreme Places', 'Category': 'Siberia'},
    {'Topic': 'Extreme Places', 'Category': 'Verkhoyansk'},
    {'Topic': 'Extreme Places', 'Category': 'Vostok Station'},
    {'Topic': 'Extreme Places', 'Category': 'Greenland Ice Sheet'},
    {'Topic': 'Extreme Places', 'Category': 'Patagonian Ice Field'},
    {'Topic': 'Extreme Places', 'Category': 'Vatnajokull'},
    {'Topic': 'Extreme Places', 'Category': 'Mount Erebus'},
    {'Topic': 'Extreme Places', 'Category': 'Mount Etna'},
    {'Topic': 'Extreme Places', 'Category': 'Kilauea'},
    {'Topic': 'Extreme Places', 'Category': 'Yellowstone'},
    {'Topic': 'Extreme Places', 'Category': 'Hverir'},
    {'Topic': 'Extreme Places', 'Category': 'Dallol'},
    {'Topic': 'Extreme Places', 'Category': 'Socotra'},
    {'Topic': 'Extreme Places', 'Category': 'Easter Island'},
    {'Topic': 'Extreme Places', 'Category': 'Tristan da Cunha'},
    {'Topic': 'Extreme Places', 'Category': 'Bouvet Island'},
    {'Topic': 'Extreme Places', 'Category': 'North Sentinel Island'},
    {'Topic': 'Extreme Places', 'Category': 'Pitcairn Island'},
    {'Topic': 'Extreme Places', 'Category': 'Lake Assal'},
    {'Topic': 'Extreme Places', 'Category': 'Lake Natron'},
    {'Topic': 'Extreme Places', 'Category': 'Lake Titicaca'},
    {'Topic': 'Extreme Places', 'Category': 'Lake Vostok'},
    {'Topic': 'Extreme Places', 'Category': 'Cave of Swallows'},
    {'Topic': 'Extreme Places', 'Category': 'Veryovkina Cave'},
    {'Topic': 'Extreme Places', 'Category': 'Krubera Cave'},
    {'Topic': 'Extreme Places', 'Category': 'Son Doong Cave'},
    {'Topic': 'Extreme Places', 'Category': 'Waitomo Caves'},
    {'Topic': 'Extreme Places', 'Category': 'Mountains Under Ice'},
    {'Topic': 'Extreme Places', 'Category': 'Extreme Canyons'},

    # ==================== STRANGE DISCOVERIES ====================
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient DNA Finds'},
    {'Topic': 'Strange Discoveries', 'Category': 'Frozen Mammoths'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ice Age Bodies'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Footprints'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unknown Fossils'},
    {'Topic': 'Strange Discoveries', 'Category': 'Rare Fossil Eggs'},
    {'Topic': 'Strange Discoveries', 'Category': 'Fossilized Skin'},
    {'Topic': 'Strange Discoveries', 'Category': 'Fossilized Blood'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Viruses'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Microbes'},
    {'Topic': 'Strange Discoveries', 'Category': 'New Species'},
    {'Topic': 'Strange Discoveries', 'Category': 'Deep Sea Species'},
    {'Topic': 'Strange Discoveries', 'Category': 'Cave Species'},
    {'Topic': 'Strange Discoveries', 'Category': 'Underground Ecosystems'},
    {'Topic': 'Strange Discoveries', 'Category': 'Glowing Organisms'},
    {'Topic': 'Strange Discoveries', 'Category': 'Transparent Animals'},
    {'Topic': 'Strange Discoveries', 'Category': 'Regenerating Animals'},
    {'Topic': 'Strange Discoveries', 'Category': 'Extremophile Organisms'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Seeds'},
    {'Topic': 'Strange Discoveries', 'Category': 'Giant Plants'},
    {'Topic': 'Strange Discoveries', 'Category': 'Rare Flowers'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unusual Minerals'},
    {'Topic': 'Strange Discoveries', 'Category': 'Meteorite Finds'},
    {'Topic': 'Strange Discoveries', 'Category': 'Space Rocks'},
    {'Topic': 'Strange Discoveries', 'Category': 'Interstellar Objects'},
    {'Topic': 'Strange Discoveries', 'Category': 'Hidden Galaxies'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Galaxies'},
    {'Topic': 'Strange Discoveries', 'Category': 'Rogue Planets'},
    {'Topic': 'Strange Discoveries', 'Category': 'Diamond Planets'},
    {'Topic': 'Strange Discoveries', 'Category': 'Water Planets'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unexpected Exoplanets'},
    {'Topic': 'Strange Discoveries', 'Category': 'Mysterious Radio Signals'},
    {'Topic': 'Strange Discoveries', 'Category': 'Cosmic Anomalies'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unknown Sounds'},
    {'Topic': 'Strange Discoveries', 'Category': 'Underwater Structures'},
    {'Topic': 'Strange Discoveries', 'Category': 'Sunken Forests'},
    {'Topic': 'Strange Discoveries', 'Category': 'Submerged Cities'},
    {'Topic': 'Strange Discoveries', 'Category': 'Hidden Chambers'},
    {'Topic': 'Strange Discoveries', 'Category': 'Secret Passages'},
    {'Topic': 'Strange Discoveries', 'Category': 'Buried Settlements'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unexpected Archaeology'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Clothing'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Tattoos'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Prosthetics'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Dental Work'},
    {'Topic': 'Strange Discoveries', 'Category': 'Ancient Surgery'},
    {'Topic': 'Strange Discoveries', 'Category': 'Accidental Scientific Finds'},
    {'Topic': 'Strange Discoveries', 'Category': 'Unexpected Inventions'},
    {'Topic': 'Strange Discoveries', 'Category': 'Scientific Oddities'},

    # ==================== ANCIENT CIVILIZATIONS ====================
    {'Topic': 'Ancient Civilizations', 'Category': 'Sumerians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Akkadians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Assyrians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Hittites'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Elamites'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Mitanni'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Urartu'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Phoenicians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Carthaginians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Etruscans'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Minoans'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Mycenaeans'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Scythians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Sarmatians'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Nabataeans'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Aksumites'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Kushites'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Ptolemies'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Mauryan Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Gupta Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Chola Kingdom'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Satavahanas'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Kushan Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Han Dynasty'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Qin Dynasty'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Zhou Dynasty'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Shang Dynasty'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Maya Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Aztec Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Inca Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Olmec Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Zapotec Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Moche Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Nazca Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Tiwanaku Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Mississippian Culture'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Norte Chico Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Dilmun Civilization'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Minoan Palaces'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Mycenaean Palaces'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Persian Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Achaemenid Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Parthian Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Sassanian Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Byzantine Empire'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Celtic Tribes'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Norse Culture'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Etruscan Cities'},
    {'Topic': 'Ancient Civilizations', 'Category': 'Ancient African Kingdoms'},

    # ==================== LOST CIVILIZATIONS ====================
    {'Topic': 'Lost Civilizations', 'Category': 'Dilmun'},
    {'Topic': 'Lost Civilizations', 'Category': 'Minoan Cities'},
    {'Topic': 'Lost Civilizations', 'Category': 'Mycenaean Cities'},
    {'Topic': 'Lost Civilizations', 'Category': 'Etruscan Cities'},
    {'Topic': 'Lost Civilizations', 'Category': 'Cahokia'},
    {'Topic': 'Lost Civilizations', 'Category': 'Great Zimbabwe'},
    {'Topic': 'Lost Civilizations', 'Category': 'Nan Madol'},
    {'Topic': 'Lost Civilizations', 'Category': 'Tikal'},
    {'Topic': 'Lost Civilizations', 'Category': 'Copan'},
    {'Topic': 'Lost Civilizations', 'Category': 'Calakmul'},
    {'Topic': 'Lost Civilizations', 'Category': 'Teotihuacan'},
    {'Topic': 'Lost Civilizations', 'Category': 'Palenque'},
    {'Topic': 'Lost Civilizations', 'Category': 'Chichen Itza'},
    {'Topic': 'Lost Civilizations', 'Category': 'Caral'},
    {'Topic': 'Lost Civilizations', 'Category': 'Chan Chan'},
    {'Topic': 'Lost Civilizations', 'Category': 'Tiwanaku'},
    {'Topic': 'Lost Civilizations', 'Category': 'Akrotiri'},
    {'Topic': 'Lost Civilizations', 'Category': 'Knossos'},
    {'Topic': 'Lost Civilizations', 'Category': 'Hattusa'},
    {'Topic': 'Lost Civilizations', 'Category': 'Ugarit'},
    {'Topic': 'Lost Civilizations', 'Category': 'Mari'},
    {'Topic': 'Lost Civilizations', 'Category': 'Ur'},
    {'Topic': 'Lost Civilizations', 'Category': 'Nineveh'},
    {'Topic': 'Lost Civilizations', 'Category': 'Nimrud'},
    {'Topic': 'Lost Civilizations', 'Category': 'Persepolis'},
    {'Topic': 'Lost Civilizations', 'Category': 'Ctesiphon'},
    {'Topic': 'Lost Civilizations', 'Category': 'Ani'},
    {'Topic': 'Lost Civilizations', 'Category': 'Merv'},
    {'Topic': 'Lost Civilizations', 'Category': 'Palmyra'},
    {'Topic': 'Lost Civilizations', 'Category': 'Leptis Magna'},
    {'Topic': 'Lost Civilizations', 'Category': 'Carthage Ruins'},
    {'Topic': 'Lost Civilizations', 'Category': 'Thonis Heracleion'},
    {'Topic': 'Lost Civilizations', 'Category': 'Canopus'},
    {'Topic': 'Lost Civilizations', 'Category': 'Dunwich'},
    {'Topic': 'Lost Civilizations', 'Category': 'Helike'},
    {'Topic': 'Lost Civilizations', 'Category': 'Pavlopetri'},
    {'Topic': 'Lost Civilizations', 'Category': 'Port Royal'},
    {'Topic': 'Lost Civilizations', 'Category': 'Lothal'},
    {'Topic': 'Lost Civilizations', 'Category': 'Dholavira'},
    {'Topic': 'Lost Civilizations', 'Category': 'Rakhigarhi'},
    {'Topic': 'Lost Civilizations', 'Category': 'Kalibangan'},
    {'Topic': 'Lost Civilizations', 'Category': 'Taxila'},
    {'Topic': 'Lost Civilizations', 'Category': 'Vijayanagara Ruins'},
    {'Topic': 'Lost Civilizations', 'Category': 'Maya Abandoned Cities'},
    {'Topic': 'Lost Civilizations', 'Category': 'Deserted Roman Cities'},
    {'Topic': 'Lost Civilizations', 'Category': 'Buried Ancient Towns'},
    {'Topic': 'Lost Civilizations', 'Category': 'Sunken Settlements'},
    {'Topic': 'Lost Civilizations', 'Category': 'Forgotten Kingdoms'},
    {'Topic': 'Lost Civilizations', 'Category': 'Vanished Peoples'},

    # ==================== FUTURE TECHNOLOGY ====================
    {'Topic': 'Future Technology', 'Category': 'Quantum Internet'},
    {'Topic': 'Future Technology', 'Category': 'Quantum Cryptography'},
    {'Topic': 'Future Technology', 'Category': 'Photonic Computers'},
    {'Topic': 'Future Technology', 'Category': 'Neuromorphic Computers'},
    {'Topic': 'Future Technology', 'Category': 'Optical Computing'},
    {'Topic': 'Future Technology', 'Category': 'DNA Computing'},
    {'Topic': 'Future Technology', 'Category': 'Molecular Machines'},
    {'Topic': 'Future Technology', 'Category': 'Nanorobots'},
    {'Topic': 'Future Technology', 'Category': 'Medical Nanobots'},
    {'Topic': 'Future Technology', 'Category': 'Artificial Organs'},
    {'Topic': 'Future Technology', 'Category': 'Lab Grown Organs'},
    {'Topic': 'Future Technology', 'Category': '3D Printed Organs'},
    {'Topic': 'Future Technology', 'Category': 'Smart Prosthetics'},
    {'Topic': 'Future Technology', 'Category': 'Bionic Limbs'},
    {'Topic': 'Future Technology', 'Category': 'Artificial Retinas'},
    {'Topic': 'Future Technology', 'Category': 'Neural Implants'},
    {'Topic': 'Future Technology', 'Category': 'Brain Implants'},
    {'Topic': 'Future Technology', 'Category': 'Mind Uploading'},
    {'Topic': 'Future Technology', 'Category': 'Digital Humans'},
    {'Topic': 'Future Technology', 'Category': 'Digital Twins'},
    {'Topic': 'Future Technology', 'Category': 'Synthetic Humans'},
    {'Topic': 'Future Technology', 'Category': 'Gene Drives'},
    {'Topic': 'Future Technology', 'Category': 'CRISPR Technology'},
    {'Topic': 'Future Technology', 'Category': 'Synthetic Genomes'},
    {'Topic': 'Future Technology', 'Category': 'Cell Programming'},
    {'Topic': 'Future Technology', 'Category': 'Longevity Technology'},
    {'Topic': 'Future Technology', 'Category': 'Anti Aging Technology'},
    {'Topic': 'Future Technology', 'Category': 'Fusion Reactors'},
    {'Topic': 'Future Technology', 'Category': 'Solar Space Power'},
    {'Topic': 'Future Technology', 'Category': 'Wireless Power'},
    {'Topic': 'Future Technology', 'Category': 'Solid State Batteries'},
    {'Topic': 'Future Technology', 'Category': 'Sodium Ion Batteries'},
    {'Topic': 'Future Technology', 'Category': 'Hydrogen Technology'},
    {'Topic': 'Future Technology', 'Category': 'Carbon Capture'},
    {'Topic': 'Future Technology', 'Category': 'Artificial Photosynthesis'},
    {'Topic': 'Future Technology', 'Category': 'Smart Glass'},
    {'Topic': 'Future Technology', 'Category': 'Programmable Matter'},
    {'Topic': 'Future Technology', 'Category': 'Metamaterials'},
    {'Topic': 'Future Technology', 'Category': 'Invisible Materials'},
    {'Topic': 'Future Technology', 'Category': 'Self Healing Concrete'},
    {'Topic': 'Future Technology', 'Category': 'Self Cleaning Materials'},
    {'Topic': 'Future Technology', 'Category': 'Shape Shifting Materials'},
    {'Topic': 'Future Technology', 'Category': 'Robotic Exoskeletons'},
    {'Topic': 'Future Technology', 'Category': 'Swarm Robotics'},
    {'Topic': 'Future Technology', 'Category': 'Soft Robots'},
    {'Topic': 'Future Technology', 'Category': 'Nanomaterials'},
    {'Topic': 'Future Technology', 'Category': 'Smart Contact Lenses'},
    {'Topic': 'Future Technology', 'Category': 'Haptic Technology'},
    {'Topic': 'Future Technology', 'Category': 'Spatial Computing'},

    # ==================== TIME TRAVEL ====================
    {'Topic': 'Time Travel', 'Category': 'Future Time Travel'},
    {'Topic': 'Time Travel', 'Category': 'Past Time Travel'},
    {'Topic': 'Time Travel', 'Category': 'Twin Paradox'},
    {'Topic': 'Time Travel', 'Category': 'Time Dilation'},
    {'Topic': 'Time Travel', 'Category': 'Gravitational Time'},
    {'Topic': 'Time Travel', 'Category': 'Relativistic Travel'},
    {'Topic': 'Time Travel', 'Category': 'Light Speed Travel'},
    {'Topic': 'Time Travel', 'Category': 'Near Light Speed'},
    {'Topic': 'Time Travel', 'Category': 'Wormhole Travel'},
    {'Topic': 'Time Travel', 'Category': 'Traversable Wormholes'},
    {'Topic': 'Time Travel', 'Category': 'Closed Timelike Curves'},
    {'Topic': 'Time Travel', 'Category': 'Causal Loops'},
    {'Topic': 'Time Travel', 'Category': 'Bootstrap Paradox'},
    {'Topic': 'Time Travel', 'Category': 'Grandfather Paradox'},
    {'Topic': 'Time Travel', 'Category': 'Predestination Paradox'},
    {'Topic': 'Time Travel', 'Category': 'Newcomb Paradox'},
    {'Topic': 'Time Travel', 'Category': 'Temporal Causality'},
    {'Topic': 'Time Travel', 'Category': 'Chronology Protection'},
    {'Topic': 'Time Travel', 'Category': 'Novikov Principle'},
    {'Topic': 'Time Travel', 'Category': 'Retrocausality'},
    {'Topic': 'Time Travel', 'Category': 'Quantum Time Travel'},
    {'Topic': 'Time Travel', 'Category': 'Quantum Causality'},
    {'Topic': 'Time Travel', 'Category': 'Many Worlds Time Travel'},
    {'Topic': 'Time Travel', 'Category': 'Parallel Timeline Travel'},
    {'Topic': 'Time Travel', 'Category': 'Time Machines'},
    {'Topic': 'Time Travel', 'Category': 'Time Machine Physics'},
    {'Topic': 'Time Travel', 'Category': 'Time Loops'},
    {'Topic': 'Time Travel', 'Category': 'Temporal Wormholes'},
    {'Topic': 'Time Travel', 'Category': 'Spacetime Curvature'},
    {'Topic': 'Time Travel', 'Category': 'Rotating Universes'},
    {'Topic': 'Time Travel', 'Category': 'Cosmic Strings'},
    {'Topic': 'Time Travel', 'Category': 'Tipler Cylinder'},
    {'Topic': 'Time Travel', 'Category': 'Alcubierre Drive'},
    {'Topic': 'Time Travel', 'Category': 'Warp Travel'},
    {'Topic': 'Time Travel', 'Category': 'Time Reversal'},
    {'Topic': 'Time Travel', 'Category': 'Entropy and Time'},
    {'Topic': 'Time Travel', 'Category': 'Arrow of Time'},
    {'Topic': 'Time Travel', 'Category': 'Quantum Retrocausality'},
    {'Topic': 'Time Travel', 'Category': 'Temporal Information'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Experiments'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Simulations'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Paradoxes'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Theories'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Mathematics'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Relativity'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Black Holes'},
    {'Topic': 'Time Travel', 'Category': 'Time Travel Wormholes'},
    {'Topic': 'Time Travel', 'Category': 'Temporal Physics'},
    {'Topic': 'Time Travel', 'Category': 'Causal Structure'},

    # ==================== PARALLEL UNIVERSE ====================
    {'Topic': 'Parallel Universe', 'Category': 'Many Worlds Interpretation'},
    {'Topic': 'Parallel Universe', 'Category': 'Bubble Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Brane Worlds'},
    {'Topic': 'Parallel Universe', 'Category': 'Quantum Branches'},
    {'Topic': 'Parallel Universe', 'Category': 'Alternate Timelines'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Earths'},
    {'Topic': 'Parallel Universe', 'Category': 'Alternate Realities'},
    {'Topic': 'Parallel Universe', 'Category': 'Mirror Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Pocket Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Baby Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Eternal Inflation'},
    {'Topic': 'Parallel Universe', 'Category': 'Cosmic Landscape'},
    {'Topic': 'Parallel Universe', 'Category': 'String Theory'},
    {'Topic': 'Parallel Universe', 'Category': 'Extra Dimensions'},
    {'Topic': 'Parallel Universe', 'Category': 'Higher Dimensions'},
    {'Topic': 'Parallel Universe', 'Category': 'Brane Cosmology'},
    {'Topic': 'Parallel Universe', 'Category': 'M Theory'},
    {'Topic': 'Parallel Universe', 'Category': 'Quantum Branching'},
    {'Topic': 'Parallel Universe', 'Category': 'Quantum Realities'},
    {'Topic': 'Parallel Universe', 'Category': 'Quantum Worlds'},
    {'Topic': 'Parallel Universe', 'Category': 'Alternate Histories'},
    {'Topic': 'Parallel Universe', 'Category': 'Alternate Earths'},
    {'Topic': 'Parallel Universe', 'Category': 'Mirror Earths'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Civilizations'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Life'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Biology'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Physics'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Chemistry'},
    {'Topic': 'Parallel Universe', 'Category': 'Parallel Dimensions'},
    {'Topic': 'Parallel Universe', 'Category': 'Hidden Dimensions'},
    {'Topic': 'Parallel Universe', 'Category': 'Extra Spatial Dimensions'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Models'},
    {'Topic': 'Parallel Universe', 'Category': 'Level One Multiverse'},
    {'Topic': 'Parallel Universe', 'Category': 'Level Two Multiverse'},
    {'Topic': 'Parallel Universe', 'Category': 'Level Three Multiverse'},
    {'Topic': 'Parallel Universe', 'Category': 'Level Four Multiverse'},
    {'Topic': 'Parallel Universe', 'Category': 'Simulation Worlds'},
    {'Topic': 'Parallel Universe', 'Category': 'Digital Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Mathematical Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Infinite Universes'},
    {'Topic': 'Parallel Universe', 'Category': 'Finite Multiverse'},
    {'Topic': 'Parallel Universe', 'Category': 'Universe Collisions'},
    {'Topic': 'Parallel Universe', 'Category': 'Bubble Collisions'},
    {'Topic': 'Parallel Universe', 'Category': 'Brane Collisions'},
    {'Topic': 'Parallel Universe', 'Category': 'Universe Tunneling'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Evidence'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Tests'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Observations'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Mysteries'},
    {'Topic': 'Parallel Universe', 'Category': 'Multiverse Physics'},

    # ==================== WEIRD SCIENCE ====================
    {'Topic': 'Weird Science', 'Category': 'Superfluidity'},
    {'Topic': 'Weird Science', 'Category': 'Superconductivity'},
    {'Topic': 'Weird Science', 'Category': 'Quantum Levitation'},
    {'Topic': 'Weird Science', 'Category': 'Quantum Teleportation'},
    {'Topic': 'Weird Science', 'Category': 'Quantum Tunneling'},
    {'Topic': 'Weird Science', 'Category': 'Quantum Entanglement'},
    {'Topic': 'Weird Science', 'Category': 'Quantum Superposition'},
    {'Topic': 'Weird Science', 'Category': 'Time Crystals'},
    {'Topic': 'Weird Science', 'Category': 'Bose Einstein Condensate'},
    {'Topic': 'Weird Science', 'Category': 'Fermionic Condensate'},
    {'Topic': 'Weird Science', 'Category': 'Plasma'},
    {'Topic': 'Weird Science', 'Category': 'Non Newtonian Materials'},
    {'Topic': 'Weird Science', 'Category': 'Shear Thickening'},
    {'Topic': 'Weird Science', 'Category': 'Shear Thinning'},
    {'Topic': 'Weird Science', 'Category': 'Superhydrophobic Surfaces'},
    {'Topic': 'Weird Science', 'Category': 'Aerogel'},
    {'Topic': 'Weird Science', 'Category': 'Metal Foam'},
    {'Topic': 'Weird Science', 'Category': 'Shape Memory Alloys'},
    {'Topic': 'Weird Science', 'Category': 'Liquid Crystals'},
    {'Topic': 'Weird Science', 'Category': 'Ferrofluids'},
    {'Topic': 'Weird Science', 'Category': 'Magnetic Fluids'},
    {'Topic': 'Weird Science', 'Category': 'Self Healing Polymers'},
    {'Topic': 'Weird Science', 'Category': 'Programmable Materials'},
    {'Topic': 'Weird Science', 'Category': 'Metamaterials'},
    {'Topic': 'Weird Science', 'Category': 'Negative Refraction'},
    {'Topic': 'Weird Science', 'Category': 'Invisibility Cloaks'},
    {'Topic': 'Weird Science', 'Category': 'Optical Illusions'},
    {'Topic': 'Weird Science', 'Category': 'Acoustic Levitation'},
    {'Topic': 'Weird Science', 'Category': 'Magnetic Levitation'},
    {'Topic': 'Weird Science', 'Category': 'Sonoluminescence'},
    {'Topic': 'Weird Science', 'Category': 'Triboluminescence'},
    {'Topic': 'Weird Science', 'Category': 'Mechanoluminescence'},
    {'Topic': 'Weird Science', 'Category': 'Chemiluminescence'},
    {'Topic': 'Weird Science', 'Category': 'Electroluminescence'},
    {'Topic': 'Weird Science', 'Category': 'Bioluminescent Plants'},
    {'Topic': 'Weird Science', 'Category': 'Regenerating Animals'},
    {'Topic': 'Weird Science', 'Category': 'Immortal Jellyfish'},
    {'Topic': 'Weird Science', 'Category': 'Animal Regeneration'},
    {'Topic': 'Weird Science', 'Category': 'Plant Memory'},
    {'Topic': 'Weird Science', 'Category': 'Plant Electrical Signals'},
    {'Topic': 'Weird Science', 'Category': 'Plant Root Communication'},
    {'Topic': 'Weird Science', 'Category': 'Electric Bacteria'},
    {'Topic': 'Weird Science', 'Category': 'Magnetic Bacteria'},
    {'Topic': 'Weird Science', 'Category': 'Extremophile Microbes'},
    {'Topic': 'Weird Science', 'Category': 'Radiation Resistant Organisms'},
    {'Topic': 'Weird Science', 'Category': 'Ice That Burns'},
    {'Topic': 'Weird Science', 'Category': 'Metal That Remembers'},
    {'Topic': 'Weird Science', 'Category': 'Materials That Change Color'},
    {'Topic': 'Weird Science', 'Category': 'Strange Physical Effects'},

    # ==================== NATURAL PHENOMENA ====================
    {'Topic': 'Natural Phenomena', 'Category': 'Ball Lightning'},
    {'Topic': 'Natural Phenomena', 'Category': 'Fire Whirls'},
    {'Topic': 'Natural Phenomena', 'Category': 'Waterspouts'},
    {'Topic': 'Natural Phenomena', 'Category': 'Dust Devils'},
    {'Topic': 'Natural Phenomena', 'Category': 'Microbursts'},
    {'Topic': 'Natural Phenomena', 'Category': 'Derechos'},
    {'Topic': 'Natural Phenomena', 'Category': 'Supercells'},
    {'Topic': 'Natural Phenomena', 'Category': 'Sprites'},
    {'Topic': 'Natural Phenomena', 'Category': 'Blue Jets'},
    {'Topic': 'Natural Phenomena', 'Category': 'Elves'},
    {'Topic': 'Natural Phenomena', 'Category': 'Red Sprites'},
    {'Topic': 'Natural Phenomena', 'Category': 'St Elmos Fire'},
    {'Topic': 'Natural Phenomena', 'Category': 'Brocken Spectre'},
    {'Topic': 'Natural Phenomena', 'Category': 'Glory'},
    {'Topic': 'Natural Phenomena', 'Category': 'Green Flash'},
    {'Topic': 'Natural Phenomena', 'Category': 'Moonbows'},
    {'Topic': 'Natural Phenomena', 'Category': 'Sundogs'},
    {'Topic': 'Natural Phenomena', 'Category': 'Light Pillars'},
    {'Topic': 'Natural Phenomena', 'Category': 'Circumhorizontal Arc'},
    {'Topic': 'Natural Phenomena', 'Category': 'Circumzenithal Arc'},
    {'Topic': 'Natural Phenomena', 'Category': 'Fata Morgana'},
    {'Topic': 'Natural Phenomena', 'Category': 'Heat Haze'},
    {'Topic': 'Natural Phenomena', 'Category': 'Dust Storms'},
    {'Topic': 'Natural Phenomena', 'Category': 'Haboobs'},
    {'Topic': 'Natural Phenomena', 'Category': 'Microbursts'},
    {'Topic': 'Natural Phenomena', 'Category': 'Derecho Winds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Katabatic Winds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Chinook Winds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Santa Ana Winds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Monsoon'},
    {'Topic': 'Natural Phenomena', 'Category': 'El Nino'},
    {'Topic': 'Natural Phenomena', 'Category': 'La Nina'},
    {'Topic': 'Natural Phenomena', 'Category': 'Atmospheric Rivers'},
    {'Topic': 'Natural Phenomena', 'Category': 'Polar Vortices'},
    {'Topic': 'Natural Phenomena', 'Category': 'Jet Streams'},
    {'Topic': 'Natural Phenomena', 'Category': 'Cloud Streets'},
    {'Topic': 'Natural Phenomena', 'Category': 'Lenticular Clouds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Mammatus Clouds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Noctilucent Clouds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Morning Glory Clouds'},
    {'Topic': 'Natural Phenomena', 'Category': 'Fire Rainbow'},
    {'Topic': 'Natural Phenomena', 'Category': 'Volcanic Lightning'},
    {'Topic': 'Natural Phenomena', 'Category': 'Volcanic Tornadoes'},
    {'Topic': 'Natural Phenomena', 'Category': 'Lava Tubes'},
    {'Topic': 'Natural Phenomena', 'Category': 'Landslides'},
    {'Topic': 'Natural Phenomena', 'Category': 'Rockfalls'},
    {'Topic': 'Natural Phenomena', 'Category': 'Sinkholes'},
    {'Topic': 'Natural Phenomena', 'Category': 'Geysers'},
    {'Topic': 'Natural Phenomena', 'Category': 'Mud Volcanoes'},

    # ==================== WORLD RECORDS ====================
    {'Topic': 'World Records', 'Category': 'Largest Animal'},
    {'Topic': 'World Records', 'Category': 'Smallest Mammal'},
    {'Topic': 'World Records', 'Category': 'Largest Bird'},
    {'Topic': 'World Records', 'Category': 'Smallest Bird'},
    {'Topic': 'World Records', 'Category': 'Fastest Bird'},
    {'Topic': 'World Records', 'Category': 'Fastest Fish'},
    {'Topic': 'World Records', 'Category': 'Fastest Land Animal'},
    {'Topic': 'World Records', 'Category': 'Largest Reptile'},
    {'Topic': 'World Records', 'Category': 'Longest Snake'},
    {'Topic': 'World Records', 'Category': 'Largest Snake'},
    {'Topic': 'World Records', 'Category': 'Largest Frog'},
    {'Topic': 'World Records', 'Category': 'Largest Butterfly'},
    {'Topic': 'World Records', 'Category': 'Largest Insect'},
    {'Topic': 'World Records', 'Category': 'Largest Spider'},
    {'Topic': 'World Records', 'Category': 'Largest Flower'},
    {'Topic': 'World Records', 'Category': 'Tallest Tree'},
    {'Topic': 'World Records', 'Category': 'Oldest Tree'},
    {'Topic': 'World Records', 'Category': 'Largest Tree'},
    {'Topic': 'World Records', 'Category': 'Largest Seed'},
    {'Topic': 'World Records', 'Category': 'Largest Fruit'},
    {'Topic': 'World Records', 'Category': 'Largest Country'},
    {'Topic': 'World Records', 'Category': 'Smallest Country'},
    {'Topic': 'World Records', 'Category': 'Largest Island'},
    {'Topic': 'World Records', 'Category': 'Longest River'},
    {'Topic': 'World Records', 'Category': 'Largest Lake'},
    {'Topic': 'World Records', 'Category': 'Deepest Lake'},
    {'Topic': 'World Records', 'Category': 'Highest Waterfall'},
    {'Topic': 'World Records', 'Category': 'Largest Waterfall System'},
    {'Topic': 'World Records', 'Category': 'Largest Cave'},
    {'Topic': 'World Records', 'Category': 'Deepest Cave'},
    {'Topic': 'World Records', 'Category': 'Longest Cave'},
    {'Topic': 'World Records', 'Category': 'Largest Canyon'},
    {'Topic': 'World Records', 'Category': 'Longest Canyon'},
    {'Topic': 'World Records', 'Category': 'Tallest Mountain'},
    {'Topic': 'World Records', 'Category': 'Largest Volcano'},
    {'Topic': 'World Records', 'Category': 'Largest Desert'},
    {'Topic': 'World Records', 'Category': 'Largest Rainforest'},
    {'Topic': 'World Records', 'Category': 'Largest Coral Reef'},
    {'Topic': 'World Records', 'Category': 'Largest Dam'},
    {'Topic': 'World Records', 'Category': 'Longest Railway'},
    {'Topic': 'World Records', 'Category': 'Longest Highway'},
    {'Topic': 'World Records', 'Category': 'Longest Road Tunnel'},
    {'Topic': 'World Records', 'Category': 'Longest Suspension Bridge'},
    {'Topic': 'World Records', 'Category': 'Largest Airport'},
    {'Topic': 'World Records', 'Category': 'Largest Port'},
    {'Topic': 'World Records', 'Category': 'Largest Cruise Ship'},
    {'Topic': 'World Records', 'Category': 'Largest Cargo Ship'},
    {'Topic': 'World Records', 'Category': 'Largest Passenger Aircraft'},
    {'Topic': 'World Records', 'Category': 'Longest Nonstop Flight'},
    {'Topic': 'World Records', 'Category': 'Fastest Aircraft'},
]

def aggressive_create_file(repo, path, message, content):
    """File create karne ka aggressive function jo errors (jaise duplicate file) handle karega"""
    try:
        repo.create_file(path=path, message=message, content=content, branch="main")
        return True, "✅ Created"
    except GithubException as e:
        # 422 ka matlab hai file/folder pehle se exist karta hai
        if e.status == 422:
            return False, "⏭️ Skipped (Already exists)"
        # 403 ka matlab GitHub ne request speed ki wajah se temporarily roka hai
        elif e.status == 403:
            time.sleep(2) # 2 second ka pause lekar wapas try karega
            try:
                repo.create_file(path=path, message=message, content=content, branch="main")
                return True, "✅ Created on Retry"
            except GithubException as retry_e:
                if retry_e.status == 422:
                    return False, "⏭️ Skipped (Already exists)"
                return False, f"❌ Failed on Retry: {retry_e.data.get('message', str(retry_e))}"
        else:
            return False, f"❌ Error: {e.data.get('message', str(e))}"

def create_github_files():
    print("🚀 Starting ULTRA-FAST Folder Generation...")
    
    if not GITHUB_TOKEN:
        print("❌ Error: GH_TOKEN secret is not set!")
        return

    try:
        auth = Auth.Token(GITHUB_TOKEN)
        g = Github(auth=auth)
        repo = g.get_repo(REPO_NAME)
        print(f"✅ Connected to repository: {REPO_NAME}")
    except Exception as e:
        print(f"❌ GitHub connection failed: {e}")
        return

    print(f"✅ Loaded {len(DATA)} topics directly from code. Checking for duplicates...\n")
    print("-" * 50)
    
    # Fast loop direct list se chalega
    for index, row in enumerate(DATA):
        main_topic = str(row['Topic']).strip()      
        sub_category = str(row['Category']).strip() 
        
        facts_path = f"Topics/{main_topic}/{sub_category}/facts.txt"
        images_path = f"Topics/{main_topic}/{sub_category}/images/1.txt"
        
        print(f"⚡ [{index + 1}/{len(DATA)}] {main_topic} -> {sub_category}")
        
        # Create facts.txt quickly
        status1, msg1 = aggressive_create_file(
            repo, facts_path, 
            f"Auto: Facts for {sub_category}", 
            f"Here are amazing facts about {sub_category}."
        )
        print(f"  ├── {msg1}: {facts_path}")

        # Create images/1.txt quickly
        status2, msg2 = aggressive_create_file(
            repo, images_path, 
            f"Auto: Image for {sub_category}", 
            f"Image URL for {sub_category} will be saved here."
        )
        print(f"  └── {msg2}: {images_path}")
            
    print("-" * 50)
    print("🎉 ALL DONE! Script execution finished.")

if __name__ == "__main__":
    create_github_files()
