name: Download and Upload AI Models

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    paths:
      - 'filelink.txt' # Automatically runs if you update the links

jobs:
  transfer-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Transfer Script
        env:
          SHREE_API_KEY: ${{ secrets.SHREE_API_KEY }}
        run: python upload_script.py
